### ISSUE TITLE
hw6-birthday-problem

### ISSUE THREAD

**Issue by eanelson01** [opark03/ds2006-park-olivia#6]
Grade: 1

For Question 1: Can you include the code for your calculation of the probability if the class size is 55?

For Question 7: It isn't necessarily that 11 classes had to be generated beforehand, but rather the first duplicate was with the 11th student that had a duplicate birthday. 

Great job on the rest!

**Comment by opark03** [comment]
I have resubmitted to include the code for question 1!

**Comment by eanelson01** [comment]
Grade: 2

Great job!
